modLoader="javafml" #mandatory

loaderVersion="[41,)" #mandatory (40 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="easy_emerald" #mandatory
version="1.4.15" #mandatory
displayName="Easy Emerald" #mandatory
description='''
Gear made from gems
'''


[[dependencies.easy_emerald]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.easy_emerald]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"
